# Android 特定配置
appId: com.expohakka.example
platform: android

# 全局设置
env:
  PLATFORM: android
  
# 默认等待时间
defaultTimeout: 10000

# 设备配置
device:
  # 可以指定特定的设备 ID
  # deviceId: "emulator-5554"
  
# 应用配置
app:
  # 应用包名
  packageName: com.expohakka.example
  # 主 Activity
  mainActivity: .MainActivity
  
# 测试配置
test:
  # 测试超时时间（毫秒）
  timeout: 30000
  # 重试次数
  retries: 2
  # 截图配置
  screenshots:
    enabled: true
    onFailure: true
    directory: "./screenshots/android"
